### ISSUE TITLE
玩家访问问题

### ISSUE THREAD

**Issue by M1hono** [ddaodan/Minecolonies-Chinese-Wiki#1]
您好，最近看到了该文档，非常感谢您对社区的付出。但我注意到您是使用github page来进行部署的，这样会导致大部分中文用户被墙掉也一直是大部分文档面临的难题，您有没有考虑使用[我的文档项目](https://docs.mihono.cn)来维护该殖民地文档呢，这个文档就是为了优化国内体验和建立一个足够好用的wiki文档而建立的，具体可以看[这个仓库](https://github.com/M1hono/CrychicDoc)。
如果打扰到了您非常抱歉。

**Comment by ddaodan** [comment]
稍微看了一下，对您的项目表示支持，但是我目前没有时间来维护这个项目（您可以看到上次修改已经是好几个月了），而目前的完成度还完全拿不出手。所以我更建议您单独立项。
